Repository Moe-Team/MysteryOnline, pull requests merged in 2019-11, with the labels that each got.

#104 Add a new form-like popup
  src/kv_files/mopopup.kv
  src/mopopup.py
  tests/test_form_popup.py
Labels: refactoring

#105 Makes tooltips efficient, ACTUAL LINUX SUPPORT
  src/icon.py
  src/main.py
Labels: blame Kivy, refactoring

#106 Youtube music thread safety, proper audio and tooltip fix
  src/icon.py
  src/inventory.py
  src/main.py
  src/ooc.py
  src/private_message_screen.py
  src/textbox.py
Labels: blame Kivy, enhancement, refactoring

#107 Add Local OOC by prefixing OOC messages with ;
  src/character_select.py
  src/irc_mo.py
  src/kv_files/loginscreen.kv
  src/main.py
  src/ooc.py
  src/set_kivy_config.py
Labels: feature

#146 Add sekrit clubs, better irc_channel_name.ini parsing
  MysteryOnline/irc_mo.py
  MysteryOnline/loginscreen.py
  irc_channel_name.ini
Labels: feature

#148 UI Stuff
  MysteryOnline/loginscreen.py
  MysteryOnline/mainscreen.py
  kv_files/loginscreen.kv
Labels: enhancement

#149 Exponential Volume Function
  MysteryOnline/inventory.py
  MysteryOnline/main.py
  MysteryOnline/ooc.py
  MysteryOnline/private_message_screen.py
  MysteryOnline/textbox.py
Labels: OH GOD OH FUCK
